---@diagnostic disable
return function(mode)
    local entities = {{Name="Sticky Fly",Anm2="monsters/stickyfly/stickyfly.anm2",HP=5,CollisionDamage=1,CollisionMass=3,CollisionRadius=17,ShadowSize=11,NumGridCollisionPoints=4,Type=161,Tags="fly",GridCollision="walls",Portrait=0,}, 
{Name="Toast",Anm2="monsters/toast/monster_toast.anm2",HP=10,Champion=true,CollisionMass=15,CollisionRadius=13,Friction=0,ShadowSize=25,NumGridCollisionPoints=12,Type=161,Variant=1,Portrait=1,}, 
{Name="Larry King Jr",Anm2="monsters/larrykingjr/larrykingjr.anm2",HP=13,CollisionDamage=1,CollisionMass=37,CollisionRadius=15,ShadowSize=15,NumGridCollisionPoints=8,Type=161,Variant=2,GridCollision="walls",Portrait=2,}, 
{Name="Patient",Anm2="monsters/patient/patient.anm2",HP=15,Champion=true,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=4,HasFloorAlts="false",Portrait=4,}, 
{Name="Patient (Virus)",Anm2="monsters/patient/patient.anm2",HP=15,Champion=true,CollisionDamage=2,CollisionMass=8,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=4,Subtype=1,HasFloorAlts="false",Portrait=4,}, 
{Name="Patient (Speed Ball)",Anm2="monsters/patient/patient.anm2",HP=13,Champion=true,CollisionDamage=1,CollisionMass=4,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=4,Subtype=2,HasFloorAlts="false",Portrait=4,}, 
{Name="Patient (Roid Rage)",Anm2="monsters/patient/patient.anm2",HP=17,Champion=true,CollisionDamage=1,CollisionMass=6,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=4,Subtype=3,HasFloorAlts="false",Portrait=4,}, 
{Name="Patient (Experimental Treatment)",Anm2="monsters/patient/patient.anm2",HP=15,Champion=true,CollisionDamage=1,CollisionMass=7,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=4,Subtype=4,HasFloorAlts="false",Portrait=4,}, 
{Name="Patient (Growth Hormones)",Anm2="monsters/patient/patient.anm2",HP=20,Champion=true,CollisionDamage=1,CollisionMass=10,CollisionRadius=13,ShadowSize=16,NumGridCollisionPoints=12,Type=161,Variant=4,Subtype=5,HasFloorAlts="false",Portrait=4,}, 
{Name="Patient (Synthoil)",Anm2="monsters/patient/patient.anm2",HP=17,Champion=true,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=4,Subtype=6,HasFloorAlts="false",Portrait=4,}, 
{Name="Patient (Adrenaline)",Anm2="monsters/patient/patient.anm2",HP=18,Champion=true,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=4,Subtype=7,HasFloorAlts="false",Portrait=4,}, 
{Name="Patient (Euthanasia)",Anm2="monsters/patient/patient.anm2",HP=15,Champion=true,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=4,Subtype=8,HasFloorAlts="false",Portrait=4,}, 
{Name="Cowpat",Anm2="monsters/cowpat/cowpat.anm2",HP=10,StageHP=4,CollisionDamage=1,CollisionMass=50,CollisionRadius=12,ShadowSize=20,NumGridCollisionPoints=8,Type=161,Variant=5,HasFloorAlts="true",Portrait=651,}, 
{Name="Snidge",Anm2="monsters/snidge/snidge.anm2",HP="0.1",CollisionMass=3,CollisionRadius=5,ShadowSize=1,Type=161,Variant=6,Tags="fly",GridCollision="walls",ShutDoors="false",Portrait=6,}, 
{Name="Horf On A Stick",Anm2="monsters/horfonastick/horfonastick.anm2",HP=15,Champion=true,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=15,NumGridCollisionPoints=12,Type=161,Variant=7,ShutDoors="false",Portrait=7,}, 
{Name="Dunglivery",Anm2="monsters/dunglivery/dunglivery.anm2",HP=15,StageHP=2,Champion=true,CollisionDamage=1,CollisionMass=4,CollisionRadius=10,ShadowSize=11,NumGridCollisionPoints=12,Type=161,Variant=9,Tags="fly",GridCollision="walls",Portrait=9,}, 
{Name="Floater",Anm2="monsters/floater/floater.anm2",HP=10,StageHP=3,Champion=true,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=16,NumGridCollisionPoints=12,Type=161,Variant=11,HasFloorAlts="true",Portrait=11,}, 
{Name="Fivehead",Anm2="monsters/fivehead/fivehead.anm2",HP=15,Champion=true,CollisionDamage=1,CollisionMass=40,CollisionRadius=13,Friction="0.1",ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=12,HasFloorAlts="true",Portrait=12,}, 
{Name="Onehead",Anm2="monsters/onehead/onehead.anm2",HP=7,CollisionDamage=1,CollisionMass=20,CollisionRadius=6,Friction="0.1",ShadowSize=7,NumGridCollisionPoints=12,Type=161,Variant=13,Subtype=1,HasFloorAlts="true",Portrait=13,}, 
{Name="Log",Anm2="monsters/log/log.anm2",HP=5,CollisionDamage=1,CollisionMass=2,CollisionRadius=3,ShadowSize=5,NumGridCollisionPoints=4,Type=161,Variant=16,Portrait=16,}, 
{Name="Neutral Fly",Anm2="monsters/neutralfly/neutralfly.anm2",HP=15,Champion=true,CollisionDamage=1,CollisionMass=6,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=8,Type=161,Variant=21,Tags="fly",GridCollision="walls",Portrait=22,}, 
{Name="Gobbo",Anm2="monsters\\gobbo_and_sho/monster_gobbo.anm2",HP=11,StageHP=1,Champion=true,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=26,HasFloorAlts="true",Portrait=26,}, 
{Name="Sho",Anm2="monsters\\gobbo_and_sho/monster_sho.anm2",HP=10,StageHP=1,CollisionDamage=1,CollisionMass=20,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=27,Portrait=27,}, 
{Name="Stoner",Anm2="monsters/stoner/stoner.anm2",HP=20,CollisionMass=10,CollisionRadius=20,NumGridCollisionPoints=20,Type=161,Variant=30,Tags="noreroll",ShutDoors="false",Portrait=30,}, 
{Name="Sack Kid",Anm2="monsters/sackkid/sackkid.anm2",HP=10,CollisionDamage=1,CollisionMass=2,CollisionRadius=8,ShadowSize=12,NumGridCollisionPoints=8,Type=161,Variant=35,HasFloorAlts="true",Portrait=35,}, 
{Name="Silly",Anm2="monsters/sillyandstring/silly.anm2",HP=10,CollisionDamage=1,CollisionMass=40,CollisionRadius=10,ShadowSize=15,NumGridCollisionPoints=12,Type=161,Variant=36,Portrait=36,}, 
{Name="String",Anm2="monsters/sillyandstring/string.anm2",HP=10,CollisionDamage=1,CollisionMass=40,CollisionRadius=10,ShadowSize=15,NumGridCollisionPoints=12,Type=161,Variant=37,Portrait=37,}, 
{Name="Roach",Anm2="monsters/roach/roach.anm2",HP=5,CollisionDamage=1,CollisionMass=5,CollisionRadius=7,ShadowSize=10,NumGridCollisionPoints=12,Type=161,Variant=38,Portrait=38,}, 
{Name="Weblet",Anm2="monsters/weblet/weblet.anm2",HP=6,CollisionDamage=1,CollisionMass=5,CollisionRadius=7,ShadowSize=10,NumGridCollisionPoints=12,Type=161,Variant=44,Portrait=39,}, 
{Name="Web Mother",Anm2="monsters/webmother/webmother.anm2",HP=20,CollisionDamage=1,CollisionMass=5,CollisionRadius=15,ShadowSize=20,NumGridCollisionPoints=12,Type=161,Variant=40,CollisionRadiusXMulti="1.5",Portrait=40,}, 
{Name="Stumbling Nest",Anm2="monsters/stumblingnest/stumblingnest.anm2",HP=12,CollisionDamage=1,CollisionMass=40,CollisionRadius=10,ShadowSize=20,NumGridCollisionPoints=12,Type=161,Variant=43,Portrait=43,}, 
{Name="Yoyader",Anm2="monsters/yoyader/yoyader.anm2",HP=18,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=46,Portrait=46,}, 
{Name="Hangeslip",Anm2="monsters/hanges/hanges.anm2",HP=13,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=50,Portrait=50,}, 
{Name="Hangejump",Anm2="monsters/hanges/hanges.anm2",HP=13,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=50,Subtype=1,Portrait=50,}, 
{Name="Hangethrow",Anm2="monsters/hanges/hanges.anm2",HP=13,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=50,Subtype=2,Portrait=50,}, 
{Name="Hangekick",Anm2="monsters/hanges/hanges.anm2",HP=13,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=50,Subtype=3,Portrait=50,}, 
{Name="Dried",Anm2="monsters/dried/dried.anm2",HP=20,CollisionDamage=1,CollisionMass=40,CollisionRadius=10,ShadowSize=20,NumGridCollisionPoints=12,Type=161,Variant=41,ShutDoors="false",Portrait=41,}, 
{Name="Dried (Black)",Anm2="monsters/dried/dried.anm2",HP=20,CollisionDamage=1,CollisionMass=40,CollisionRadius=10,ShadowSize=20,NumGridCollisionPoints=12,Type=161,Variant=41,Subtype=1,ShutDoors="false",Portrait=41,}, 
{Name="Dried (White)",Anm2="monsters/dried/dried.anm2",HP=20,CollisionDamage=1,CollisionMass=40,CollisionRadius=10,ShadowSize=20,NumGridCollisionPoints=12,Type=161,Variant=41,Subtype=2,ShutDoors="false",}, 
{Name="Dried (Brown)",Anm2="monsters/dried/dried.anm2",HP=20,CollisionDamage=1,CollisionMass=40,CollisionRadius=10,ShadowSize=20,NumGridCollisionPoints=12,Type=161,Variant=41,Subtype=3,ShutDoors="false",}, 
{Name="Dried (Green)",Anm2="monsters/dried/dried.anm2",HP=20,CollisionDamage=1,CollisionMass=40,CollisionRadius=10,ShadowSize=20,NumGridCollisionPoints=12,Type=161,Variant=41,Subtype=4,ShutDoors="false",}, 
{Name="Dried (Yellow)",Anm2="monsters/dried/dried.anm2",HP=20,CollisionDamage=1,CollisionMass=40,CollisionRadius=10,ShadowSize=20,NumGridCollisionPoints=12,Type=161,Variant=41,Subtype=5,ShutDoors="false",}, 
{Name="Dried (Red)",Anm2="monsters/dried/dried.anm2",HP=20,CollisionDamage=1,CollisionMass=40,CollisionRadius=10,ShadowSize=20,NumGridCollisionPoints=12,Type=161,Variant=41,Subtype=6,ShutDoors="false",}, 
{Name="Detached Dried",Anm2="monsters/dried/detacheddried.anm2",HP=20,CollisionMass=40,CollisionRadius=10,ShadowSize=20,NumGridCollisionPoints=12,Type=161,Variant=51,CollisionRadiusXMulti=2,ShutDoors="false",Portrait=51,}, 
{Name="Detached Dried (Black)",Anm2="monsters/dried/detacheddried.anm2",HP=20,CollisionMass=40,CollisionRadius=10,ShadowSize=20,NumGridCollisionPoints=12,Type=161,Variant=51,Subtype=1,CollisionRadiusXMulti=2,ShutDoors="false",Portrait=51,}, 
{Name="Detached Dried (White)",Anm2="monsters/dried/detacheddried.anm2",HP=20,CollisionMass=40,CollisionRadius=10,ShadowSize=20,NumGridCollisionPoints=12,Type=161,Variant=51,Subtype=2,CollisionRadiusXMulti=2,ShutDoors="false",}, 
{Name="Detached Dried (Brown)",Anm2="monsters/dried/detacheddried.anm2",HP=20,CollisionMass=40,CollisionRadius=10,ShadowSize=20,NumGridCollisionPoints=12,Type=161,Variant=51,Subtype=3,CollisionRadiusXMulti=2,ShutDoors="false",}, 
{Name="Detached Dried (Green)",Anm2="monsters/dried/detacheddried.anm2",HP=20,CollisionMass=40,CollisionRadius=10,ShadowSize=20,NumGridCollisionPoints=12,Type=161,Variant=51,Subtype=4,CollisionRadiusXMulti=2,ShutDoors="false",}, 
{Name="Detached Dried (Yellow)",Anm2="monsters/dried/detacheddried.anm2",HP=20,CollisionMass=40,CollisionRadius=10,ShadowSize=20,NumGridCollisionPoints=12,Type=161,Variant=51,Subtype=5,CollisionRadiusXMulti=2,ShutDoors="false",}, 
{Name="Detached Dried (Red)",Anm2="monsters/dried/detacheddried.anm2",HP=20,CollisionMass=40,CollisionRadius=10,ShadowSize=20,NumGridCollisionPoints=12,Type=161,Variant=51,Subtype=6,CollisionRadiusXMulti=2,ShutDoors="false",}, 
{Name="The Hanged",Anm2="monsters/hanger/hanger.anm2",HP=10,StageHP=3,Champion=true,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=16,NumGridCollisionPoints=12,Type=161,Variant=53,HasFloorAlts="true",Portrait=52,}, 
{Name="Plier",Anm2="monsters/plier/plier.anm2",HP=10,Champion=true,CollisionDamage=1,CollisionMass=6,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=8,Type=161,Variant=42,Tags="fly",GridCollision="walls",Portrait=42,}, 
{Name="Woodhead",Anm2="monsters\\woodhead/woodhead.anm2",HP=12,StageHP=1,Champion=true,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=37,Variant=3,HasFloorAlts="false",Portrait=26,}, 
{Name="Small Nest",Anm2="monsters/smallnest/smallnest.anm2",HP=7,Champion=true,CollisionDamage=1,CollisionMass=5,CollisionRadius=7,ShadowSize=14,NumGridCollisionPoints=8,Type=161,Variant=45,HasFloorAlts="false",Portrait=26,}, 
{Name="Angery Man",Anm2="monsters/angeryman/angeryman.anm2",HP=15,Champion=true,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=47,HasFloorAlts="false",Portrait=47,}, 
{Name="Bewebbed",Anm2="monsters/bewebbed/bewebbed.anm2",HP=12,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=48,HasFloorAlts="false",CollisionRadiusXMulti="1.5",Portrait=48,}, 
{Name="Rehost",Anm2="monsters/rehost/rehost.anm2",HP=15,Champion=true,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=49,HasFloorAlts="true",Portrait=49,}, 
{Name="Potted Fatty",Anm2="monsters/pottedfatty/pottedfatty.anm2",HP=20,Champion=true,CollisionDamage=1,CollisionMass=10,CollisionRadius=13,ShadowSize=16,NumGridCollisionPoints=12,Type=161,Variant=52,Portrait=51,}, 
{Name="Webbed Carcass",Anm2="monsters/webbedcarcass/webbedcarcass.anm2",HP=10,Champion=true,CollisionDamage=1,CollisionMass=40,CollisionRadius=13,Friction=0,NumGridCollisionPoints=12,Type=161,Variant=59,HasFloorAlts="true",ShutDoors="false",Portrait=532,}, 
{Name="Suck Up",Anm2="monsters/suckup/suckup.anm2",HP=10,Champion="false",CollisionDamage=1,CollisionMass=3,CollisionRadius=11,ShadowSize=13,NumGridCollisionPoints=5,Type=161,Variant=65,Tags="fly",GridCollision="walls",Portrait="",}, 
{Name="Stall Creep",Anm2="monsters/stallcreep/stall_creep.anm2",HP=10,CollisionDamage=1,CollisionMass=14,CollisionRadius=13,NumGridCollisionPoints=12,Type=240,Variant=359,Portrait=660,}, 
{Name="Webbed Creep",Anm2="monsters/webbedcreep/webbed_creep.anm2",HP=12,CollisionDamage=1,CollisionMass=14,CollisionRadius=13,NumGridCollisionPoints=12,Type=240,Variant=368,Portrait=660,}, 
{Name="Hot Potato",Anm2="monsters/hotpotato/hotpotato.anm2",HP=10,Champion=true,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=71,HasFloorAlts="false",Portrait=1,}, 
{Name="Furnace",Anm2="monsters/furnace/furnace.anm2",HP=12,Champion=true,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=72,HasFloorAlts="false",Portrait=1,}, 
{Name="Scorched Sooter",Anm2="monsters/scorchedsooter/scorchedsooter.anm2",HP=18,Champion=true,CollisionDamage=1,CollisionMass=3,CollisionRadius=13,ShadowSize=13,NumGridCollisionPoints=12,Type=161,Variant=73,GridCollision="walls",Portrait=73,}, 
{Name="Facebalm",Anm2="monsters/fivehead/fivehead.anm2",HP=15,Champion=true,CollisionDamage=1,CollisionMass=40,CollisionRadius=13,Friction="0.1",ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=75,HasFloorAlts="true",Portrait=75,}, 
{Name="Crackling Host",Anm2="monsters/cracklinghost/cracklinghost.anm2",HP=10,Champion=true,CollisionMass=15,CollisionRadius=13,Friction=0,ShadowSize=25,NumGridCollisionPoints=12,Type=161,Variant=79,Portrait=1,}, 
{Name="Firehead",Anm2="monsters/firehead/firehead.anm2",HP=13,CollisionDamage=1,CollisionMass=40,CollisionRadius=13,Friction="0.1",ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=81,HasFloorAlts="true",Portrait=81,}, 
{Name="Scorched Peat",Anm2="monsters/soot/soot.anm2",HP=10,Champion=true,CollisionDamage=1,CollisionMass=3,CollisionRadius=13,ShadowSize=13,NumGridCollisionPoints=12,Type=161,Variant=80,GridCollision="walls",Portrait=80,}, 
{Name="Trilo",Anm2="monsters/trilo/trilo.anm2",HP=10,Champion=true,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=84,HasFloorAlts="false",Portrait=1,}, 
{Name="Schmoot",Anm2="monsters/schmoot/shmoot.anm2",HP=16,Champion=true,CollisionDamage=1,CollisionMass=3,CollisionRadius=13,ShadowSize=13,NumGridCollisionPoints=12,Type=161,Variant=91,Portrait=91,}, 
{Name="Lil Flash",Anm2="monsters/lilflash/lilflash.anm2",HP=7,Champion="false",CollisionDamage=1,CollisionMass=3,CollisionRadius=17,ShadowSize=11,NumGridCollisionPoints=4,Type=161,Variant=97,Tags="fly",GridCollision="walls",Portrait=97,}, 
{Name="Sulferer",Anm2="monsters/sulferer/sulferer.anm2",HP=10,Champion=true,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=100,HasFloorAlts="false",Portrait=1,}, 
{Name="Soot",Anm2="monsters/soot/soot.anm2",HP=5,Champion="false",CollisionDamage=1,CollisionMass=3,CollisionRadius=17,ShadowSize=11,NumGridCollisionPoints=4,Type=161,Variant=101,Tags="fly",GridCollision="walls",Portrait=101,}, 
{Name="Embolzon",Anm2="monsters/embolzon/embolzon.anm2",HP=12,Champion=true,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=105,HasFloorAlts="false",Portrait=105,}, 
{Name="Spaarker",Anm2="monsters/spaarker/spaarker.anm2",HP=8,Champion=true,CollisionMass=4,CollisionRadius=17,ShadowSize=11,NumGridCollisionPoints=4,Type=161,Variant=108,Tags="fly",GridCollision="walls",Portrait=6,}, 
{Name="Synthetic Horf",Anm2="monsters/synthetichorf/synthetichorf.anm2",HP=13,StageHP=1,Champion=true,CollisionDamage=1,CollisionMass=40,CollisionRadius=13,Friction="0.1",ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=189,HasFloorAlts="true",Portrait=189,}, 
{Name="Pallun",Anm2="monsters/pallun/pallun.anm2",HP=12,Champion=true,CollisionDamage=1,CollisionMass=100,CollisionRadius=13,NumGridCollisionPoints=12,Type=161,Variant=202,Portrait=202,}, 
{Name="Ulig",Anm2="monsters/ulig/ulig.anm2",HP=18,StageHP=1,Champion=true,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,NumGridCollisionPoints=12,Type=161,Variant=203,HasFloorAlts="false",Portrait=203,}, 
{Name="Sixhead Top",Anm2="monsters/sixhead/sixhead top.anm2",HP=15,StageHP=4,Champion=true,CollisionDamage=1,CollisionMass=40,CollisionRadius=13,Friction="0.1",ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=210,GridCollision="walls",HasFloorAlts="false",Portrait=210,}, 
{Name="Sixhead Bottom",Anm2="monsters/sixhead/sixhead bottom.anm2",HP=15,StageHP=1,Champion=true,CollisionDamage=1,CollisionMass=10,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=211,GridCollision="walls",HasFloorAlts="false",Portrait=211,}, 
{Name="Mush Loom",Anm2="monsters/mushloom/mushloom.anm2",HP=10,StageHP=2,CollisionDamage=1,CollisionMass=100,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=224,Portrait=224,}, 
{Name="Harmoor",Anm2="monsters/harmoor/harmoor.anm2",HP=20,StageHP=8,CollisionMass=5,CollisionRadius=13,ShadowSize=16,NumGridCollisionPoints=12,Type=161,Variant=273,Portrait=273,}, 
{Name="Pit Pat Spawner",Anm2="monsters/pitpat/pitpat.anm2",HP=20,StageHP=1,NumGridCollisionPoints=0,Type=161,Variant=278,Subtype=1,ShutDoors="false",}, 
{Name="Pit Pat",Anm2="monsters/pitpat/pitpat.anm2",HP=20,StageHP=1,Champion=true,CollisionDamage=1,CollisionMass=7,CollisionRadius=13,Friction=0,NumGridCollisionPoints=3,Type=161,Variant=278,ShutDoors="false",Portrait=278,}, 
{Name="Babble",Anm2="monsters/babble/babble.anm2",HP=13,StageHP=7,Champion=true,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=420,HasFloorAlts="true",Portrait=420,}, 
{Name="Erythorcyte",Anm2="monsters/erythorcyte/erythorcyte.anm2",HP=15,StageHP=3,Champion=true,CollisionDamage=1,CollisionMass=40,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=400,}, 
{Name="Erythorcytebaby",Anm2="monsters/erythorcyte/erythorcyte.anm2",HP=15,StageHP=2,CollisionDamage=1,CollisionMass=40,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=400,Subtype=1,}, 
{Name="Stone Johnny",Anm2="monsters/stonejohhny/stonejohhny.anm2",HP=14,Champion=true,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=109,HasFloorAlts="false",Portrait=1,}, 
{Name="Wost",Anm2="monsters/wost/wost.anm2",HP=8,StageHP=1,CollisionDamage=1,CollisionMass=40,CollisionRadius=13,ShadowSize=5,NumGridCollisionPoints=5,Type=161,Variant=119,Portrait=119,}, 
{Name="Souwa",Anm2="monsters/souwa/souwa.anm2",HP=13,Champion=true,CollisionDamage=1,CollisionMass=3,CollisionRadius=13,ShadowSize=13,NumGridCollisionPoints=12,Type=161,Variant=121,Portrait=121,}, 
{Name="Rain Monger",Anm2="monsters/rainmonger/rainmonger.anm2",HP=13,Champion=true,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=124,HasFloorAlts="true",Portrait=124,}, 
{Name="Zapper Teller",Anm2="monsters/zapperteller/zapper teller.anm2",HP=13,StageHP=2,Champion=true,CollisionDamage=1,CollisionMass=3,CollisionRadius=20,ShadowSize=20,NumGridCollisionPoints=12,Type=161,Variant=133,Portrait=133,}, 
{Name="Pinprick",Anm2="monsters/pinprick/pinprick.anm2",HP=3,StageHP=1,CollisionDamage=1,CollisionMass=3,CollisionRadius=17,ShadowSize=11,NumGridCollisionPoints=4,Type=161,Variant=145,Tags="fly",GridCollision="walls",Portrait=145,}, 
{Name="Wisp Wosp",Anm2="monsters/wispwosp/wispwosp.anm2",HP=10,Champion=true,CollisionDamage=1,CollisionMass=6,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=8,Type=161,Variant=144,Tags="fly",GridCollision="walls",Portrait=144,}, 
{Name="Drosslet",Anm2="monsters/drosslet/drosslet.anm2",HP=10,StageHP=1,CollisionDamage=1,CollisionMass=40,CollisionRadius=13,Friction="0.8",ShadowSize=5,NumGridCollisionPoints=5,Type=161,Variant=169,Portrait=169,}, 
{Name="Gassed Fly",Anm2="monsters/gassedfly/gassedfly.anm2",HP=8,Champion="",CollisionDamage=1,CollisionMass=3,CollisionRadius=17,ShadowSize=11,NumGridCollisionPoints=4,Type=161,Variant=177,Tags="fly",GridCollision="walls",Portrait=177,}, 
{Name="Stuckpoot",Anm2="monsters/stuckpoot/stuckpoot.anm2",HP=12,Champion=true,CollisionDamage=1,CollisionMass=14,CollisionRadius=13,NumGridCollisionPoints=12,Type=161,Variant=167,Portrait=93,}, 
{Name="Jim",Anm2="monsters/jim/jim.anm2",HP=10,Champion=true,CollisionDamage=1,CollisionMass=3,CollisionRadius=13,ShadowSize=13,NumGridCollisionPoints=12,Type=37,Variant=100,Portrait=37100,}, 
{Name="Tech Grudge",Anm2="monsters/techgrudge/techgrudge.anm2",HP=25,StageHP=1,Champion=true,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=15,NumGridCollisionPoints=12,Type=161,Variant=311,GridCollision="walls",Portrait=311,}, 
{Name="Fear Flower",Anm2="monsters/fear flower/fear flower.anm2",HP=30,Champion=true,CollisionDamage=1,CollisionMass=40,CollisionRadius=13,Friction=0,ShadowSize=23,NumGridCollisionPoints=12,Type=161,Variant=532,HasFloorAlts="true",Portrait=532,}, 
{Name="Clatter Teller",Anm2="monsters\\clatterteller/clatter_teller.anm2",HP=40,StageHP=3,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=25,NumGridCollisionPoints=12,Type=161,Variant=535,HasFloorAlts="true",Portrait=535,}, 
{Name="Dekatessera",Anm2="monsters\\dekatessera/dekatessera.anm2",HP=24,StageHP=3,CollisionDamage=1,CollisionMass=25,CollisionRadius=13,ShadowSize=25,NumGridCollisionPoints=12,Type=161,Variant=537,HasFloorAlts="true",Portrait=536,}, 
{Name="Fivedead",Anm2="monsters/fivedead/fivedead.anm2",HP=75,Champion=true,CollisionDamage=1,CollisionMass=40,CollisionRadius=13,Friction="0.1",ShadowSize=14,NumGridCollisionPoints=12,Type=161,Variant=12,HasFloorAlts="true",Portrait=12,}, 
{Name="Onedead",Anm2="monsters/onedead/onedead.anm2",HP=40,CollisionDamage=1,CollisionMass=20,CollisionRadius=6,Friction="0.1",ShadowSize=7,NumGridCollisionPoints=12,Type=161,Variant=13,Subtype=1,HasFloorAlts="true",Portrait=13,}, 
{Name="Tainted Silly",Anm2="monsters/tainted_silly_and_string/monster_tainted_silly.anm2",HP=70,StageHP=13,CollisionDamage=1,CollisionMass=40,CollisionRadius=10,ShadowSize=15,NumGridCollisionPoints=12,Type=426,ShieldStrength=20,Portrait=36,}, 
{Name="Tainted String",Anm2="monsters/tainted_silly_and_string/monster_tainted_string.anm2",HP=70,StageHP=13,CollisionDamage=1,CollisionMass=40,CollisionRadius=10,ShadowSize=15,NumGridCollisionPoints=12,Type=426,Variant=1,ShieldStrength=20,Portrait=36,}, 
{Name="&",Anm2="monsters/tainted_silly_and_string/monster_tainted_and.anm2",HP=20,StageHP=20,Champion=true,CollisionDamage=1,CollisionMass=10,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=426,Variant=2,ShieldStrength=1000,Portrait=37,}, 
{Name="Tainted Web Mother",Anm2="monsters/taintedwebmother/taintedwebmother.anm2",HP=70,StageHP=13,CollisionDamage=1,CollisionMass=1,NumGridCollisionPoints=12,Type=426,Variant=3,ShieldStrength=20,Portrait=36,}, 
{Name="Tainted Yoyader",Anm2="monsters/taintedyoyader/taintedyoyader.anm2",HP=55,StageHP=3,CollisionDamage=1,CollisionMass=50,CollisionRadius=15,ShadowSize=10,NumGridCollisionPoints=12,Type=426,Variant=4,CollisionRadiusXMulti="1.5",ShieldStrength=20,Portrait=36,}, 
{Name="Narcissism",Anm2="minibosses/narcissism/narcissism.anm2",HP=130,StageHP=13,Boss=true,CollisionDamage=1,CollisionMass=40,CollisionRadius=10,ShadowSize=15,NumGridCollisionPoints=12,Type=95,ShieldStrength=10,Portrait=1020,}, 
{Name="Chomb",Anm2="minibosses/chomb/monster_chomb.anm2",HP=250,StageHP=5,Boss=true,CollisionDamage=1,CollisionMass=40,CollisionRadius=10,ShadowSize=15,NumGridCollisionPoints=12,Type=95,Variant=1,ShieldStrength=10,Portrait=1021,}, 
{Name="Narcissism Reflections",Anm2="minibosses/narcissism/narcissism.anm2",HP=10,CollisionDamage=1,CollisionMass=3,CollisionRadius=10,ShadowSize=11,NumGridCollisionPoints=4,Type=37,Variant=4,GridCollision="walls",}, 
{Name="Narcissism Mirror",Anm2="minibosses/narcissism/narcissism.anm2",HP=10,CollisionDamage=1,CollisionMass=3,CollisionRadius=8,ShadowSize=11,NumGridCollisionPoints=4,Type=37,Variant=2,Tags="fly",GridCollision="walls",}, 
{Name="Chomblet",Anm2="monsters/chomblet/chomblet.anm2",HP=15,Champion=true,CollisionDamage=1,CollisionMass=7,CollisionRadius=13,ShadowSize=17,NumGridCollisionPoints=12,Type=37,Variant=5,Portrait=14,}, 
{Name="Sam",Anm2="minibosses/sam/sam.anm2",HP=500,StageHP=13,Boss=true,CollisionDamage=1,CollisionMass=40,CollisionRadius=50,ShadowSize=50,NumGridCollisionPoints=48,Type=95,Variant=2,ShieldStrength=500,Portrait=1020,}, 
{Name="Sam Bear Spawn",Anm2="minibosses/sam/smallsam.anm2",HP=15,Champion=true,CollisionDamage=1,CollisionMass=7,CollisionRadius=13,ShadowSize=17,NumGridCollisionPoints=12,Type=37,Variant=6,Portrait=14,}, 
{Name="Hop",Anm2="bosses\\hopperbrothers\\hop.anm2",HP=120,StageHP=20,Boss=true,CollisionDamage=1,CollisionMass=24,CollisionRadius=15,ShadowSize=45,NumGridCollisionPoints=12,Type=136,Tags="noreroll",HasFloorAlts="false",CollisionRadiusXMulti="1.75",Portrait=0,}, 
{Name="Skip",Anm2="bosses\\hopperbrothers\\skip.anm2",HP=90,StageHP=20,Boss=true,CollisionDamage=1,CollisionMass=16,CollisionRadius=15,ShadowSize=50,NumGridCollisionPoints=12,Type=136,Variant=1,Tags="noreroll",HasFloorAlts="false",CollisionRadiusXMulti="2.5",Portrait=0,}, 
{Name="Jump",Anm2="bosses\\hopperbrothers\\jump.anm2",HP=90,StageHP=20,Boss=true,CollisionDamage=1,CollisionMass=8,CollisionRadius=15,ShadowSize=32,NumGridCollisionPoints=12,Type=136,Variant=2,Tags="noreroll",HasFloorAlts="false",CollisionRadiusXMulti="1.5",Portrait=0,}, 
{Name="Chris",Anm2="bosses\\chris\\chris.anm2",HP=90,StageHP=20,Boss=true,CollisionDamage=1,CollisionMass=8,CollisionRadius=15,ShadowSize=32,NumGridCollisionPoints=12,Type=136,Variant=3,Tags="noreroll",HasFloorAlts="false",CollisionRadiusXMulti="1.5",Portrait=0,}, 
{Name="A gaper w/ three legs, why did we do this",Anm2="jokes/enemies/gaperrr/gaperrr.anm2",HP=13,StageHP=3,Champion=true,CollisionDamage=1,CollisionMass=40,CollisionRadius=13,ShadowSize=12,NumGridCollisionPoints=12,Type=10,Variant=5938,}, 
{Name="Willowalker",Anm2="jokes/enemies/willowalker/willowalker.anm2",HP=1,CollisionRadius=13,ShadowSize=12,NumGridCollisionPoints=12,Type=137,Variant=3939,}, 
{Name="Bowl of Sauerkraut",Anm2="items/pick ups/sauerkraut_pickups.anm2",CollisionMass=3,CollisionRadius=12,ShadowSize=17,NumGridCollisionPoints=24,Type=5,Variant=721,}, 
{Name="Letter To Myself",Anm2="items/pick ups/letter_to_myself.anm2",CollisionMass=3,CollisionRadius=12,ShadowSize=17,NumGridCollisionPoints=24,Type=5,Variant=722,}, 
{Name="Birthday Slice",Anm2="items/pick ups/aceslice.anm2",CollisionMass=3,CollisionRadius=12,ShadowSize=17,NumGridCollisionPoints=24,Type=5,Variant=300,Subtype=451,}, 
{Name="Birthday Slice",Anm2="items/pick ups/julioslice.anm2",CollisionMass=3,CollisionRadius=12,ShadowSize=17,NumGridCollisionPoints=24,Type=5,Variant=300,Subtype=452,}, 
{Name="Snark (Half Life)",Anm2="familiar/snark/snark.anm2",CollisionDamage=3,CollisionMass=3,CollisionRadius=13,ShadowSize=12,NumGridCollisionPoints=12,Type=3,Variant=4502,Tags="cansacrifice",}, 
{Name="Marketable Plushie Familiar",Anm2="familiar/marketableplushie/ml_marketableplushie.anm2",CollisionDamage=3,CollisionMass=3,CollisionRadius=13,ShadowSize=12,NumGridCollisionPoints=12,Type=3,Variant=4503,Tags="cansacrifice",}, 
{Name="Lil' Ana",Anm2="familiar/lilana/lilana.anm2",Champion=true,CollisionDamage=1,CollisionMass=5,CollisionRadius=13,ShadowSize=14,NumGridCollisionPoints=12,Type=3,Variant=4504,Tags="cansacrifice",HasFloorAlts="false",}, 
{Name="Breakable Pot",Anm2="grid/_breakablepot.anm2",HP=8,CollisionMass=10,CollisionRadius=20,NumGridCollisionPoints=20,Type=753,Variant=950,ShutDoors="false",Portrait=438,}, 
{Name="Blank NPC",Anm2="effects/nothing.anm2",NumGridCollisionPoints=0,Type=161,Variant=4095,ShieldStrength=0,}, 
{Name="Error Room Editor",Anm2="effects/nothing.anm2",NumGridCollisionPoints=0,Type=998,Variant=418,ShieldStrength=0,}, 
{Name="Blank Effect",Anm2="effects/nothing.anm2",NumGridCollisionPoints=0,Type=1000,Variant=419,ShieldStrength=0,}, 
{Name="Zapper Teller Lightning",Anm2="effects/lightning/zapperteller/effect_zappertellerlightning.anm2",NumGridCollisionPoints=0,Type=1000,Variant=420,ShieldStrength=0,}, 
{Name="BlackOverlayBox",Anm2="effects/blackscreen.anm2",NumGridCollisionPoints=0,Type=1000,Variant=421,ShieldStrength=0,}, 
{Name="Text Box",Anm2="effects/ruin/normaltextbox.anm2",NumGridCollisionPoints=0,Type=1000,Variant=424,ShieldStrength=0,}, 
{Name="Clatter Teller Target",Anm2="effects/target/clatterteller/effect_clatterteller_target.anm2",NumGridCollisionPoints=0,Type=1000,Variant=425,ShieldStrength=0,}, 
{Name="Fear Flower Fear",Anm2="effects/fear effect/fear flower/effect_fearflowerfear.anm2",NumGridCollisionPoints=0,Type=1000,Variant=426,ShieldStrength=0,}, 
{Name="Dekatessera Effect",Anm2="effects/nothing.anm2",NumGridCollisionPoints=0,Type=1000,Variant=427,ShieldStrength=0,}, 
{Name="Rain Grid Effect",Anm2="grid/nothing.anm2",CollisionDamage=1,CollisionRadius=4,Type=1000,Variant=432,}, 
{Name="Large Spiderweb",Anm2="effects/effect_wideweb.anm2",NumGridCollisionPoints=0,Type=1000,Variant=428,ShieldStrength=0,}, 
{Name="Fire Projectile",Anm2="grid/effect_005_fire.anm2",CollisionDamage=1,CollisionRadius=4,Type=1000,Variant=431,}, 
{Name="OGWilloWalker Box",Anm2="npcs/originalwillowwalker/ogwillobox.anm2",NumGridCollisionPoints=0,Type=1000,Variant=429,ShieldStrength=0,}, 
{Name="OGWilloWalker Font",Anm2="npcs/originalwillowwalker/ogwillofont.anm2",NumGridCollisionPoints=0,Type=1000,Variant=430,ShieldStrength=0,}, 
{Name="Ruin NPC",Anm2="npcs/ruin/skeletons/skeleton1.anm2",CollisionMass=8,CollisionRadius=13,Friction=0,ShadowSize=18,NumGridCollisionPoints=12,Type=163,HasFloorAlts="false",}, 
{Name="OGWilloWalker",Anm2="npcs/originalwillowwalker/ogwillowalker.anm2",CollisionMass=8,CollisionRadius=16,Friction=0,ShadowSize=32,NumGridCollisionPoints=12,Type=163,Variant=2,HasFloorAlts="false",CollisionRadiusXMulti="1.75",ShutDoors="false",}, 
{Name="Ember Projectile",Anm2="projectiles/projectile_ember.anm2",HP=10,CollisionDamage=1,CollisionMass=8,CollisionRadius=5,ShadowSize=10,NumGridCollisionPoints=8,Type=9,Portrait=545,}, 
{Name="HOPE Grid Spawner",Anm2="effects/ROBLOXIANERROR.anm2",CollisionMass=3,CollisionRadius=12,ShadowSize=17,NumGridCollisionPoints=24,Type=135,ShutDoors="false",}, 
{Name="Light Pressure Plate Null Entity",Anm2="blank.anm2",HP=10,Champion=true,NumGridCollisionPoints=0,Type=161,Variant=4089,}, 
{Name="Quiz Question Placement",Anm2="effects/nothing.anm2",NumGridCollisionPoints=0,Type=982,Variant=419,ShutDoors="false",ShieldStrength=0,}, 
{Name="IsMoQu Custom Grid Spawn",Anm2="effects/nothing.anm2",NumGridCollisionPoints=0,Type=634,ShutDoors="false",ShieldStrength=0,},}
    if not mode or mode == 1 then
        return entities
    elseif mode == 2 then
        return {["Sticky Fly"]=entities[1],
        ["Toast"]=entities[2],
        ["Larry King Jr"]=entities[3],
        ["Patient"]=entities[4],
        ["Patient (Virus)"]=entities[5],
        ["Patient (Speed Ball)"]=entities[6],
        ["Patient (Roid Rage)"]=entities[7],
        ["Patient (Experimental Treatment)"]=entities[8],
        ["Patient (Growth Hormones)"]=entities[9],
        ["Patient (Synthoil)"]=entities[10],
        ["Patient (Adrenaline)"]=entities[11],
        ["Patient (Euthanasia)"]=entities[12],
        ["Cowpat"]=entities[13],
        ["Snidge"]=entities[14],
        ["Horf On A Stick"]=entities[15],
        ["Dunglivery"]=entities[16],
        ["Floater"]=entities[17],
        ["Fivehead"]=entities[18],
        ["Onehead"]=entities[19],
        ["Log"]=entities[20],
        ["Neutral Fly"]=entities[21],
        ["Gobbo"]=entities[22],
        ["Sho"]=entities[23],
        ["Stoner"]=entities[24],
        ["Sack Kid"]=entities[25],
        ["Silly"]=entities[26],
        ["String"]=entities[27],
        ["Roach"]=entities[28],
        ["Weblet"]=entities[29],
        ["Web Mother"]=entities[30],
        ["Stumbling Nest"]=entities[31],
        ["Yoyader"]=entities[32],
        ["Hangeslip"]=entities[33],
        ["Hangejump"]=entities[34],
        ["Hangethrow"]=entities[35],
        ["Hangekick"]=entities[36],
        ["Dried"]=entities[37],
        ["Dried (Black)"]=entities[38],
        ["Dried (White)"]=entities[39],
        ["Dried (Brown)"]=entities[40],
        ["Dried (Green)"]=entities[41],
        ["Dried (Yellow)"]=entities[42],
        ["Dried (Red)"]=entities[43],
        ["Detached Dried"]=entities[44],
        ["Detached Dried (Black)"]=entities[45],
        ["Detached Dried (White)"]=entities[46],
        ["Detached Dried (Brown)"]=entities[47],
        ["Detached Dried (Green)"]=entities[48],
        ["Detached Dried (Yellow)"]=entities[49],
        ["Detached Dried (Red)"]=entities[50],
        ["The Hanged"]=entities[51],
        ["Plier"]=entities[52],
        ["Woodhead"]=entities[53],
        ["Small Nest"]=entities[54],
        ["Angery Man"]=entities[55],
        ["Bewebbed"]=entities[56],
        ["Rehost"]=entities[57],
        ["Potted Fatty"]=entities[58],
        ["Webbed Carcass"]=entities[59],
        ["Suck Up"]=entities[60],
        ["Stall Creep"]=entities[61],
        ["Webbed Creep"]=entities[62],
        ["Hot Potato"]=entities[63],
        ["Furnace"]=entities[64],
        ["Scorched Sooter"]=entities[65],
        ["Facebalm"]=entities[66],
        ["Crackling Host"]=entities[67],
        ["Firehead"]=entities[68],
        ["Scorched Peat"]=entities[69],
        ["Trilo"]=entities[70],
        ["Schmoot"]=entities[71],
        ["Lil Flash"]=entities[72],
        ["Sulferer"]=entities[73],
        ["Soot"]=entities[74],
        ["Embolzon"]=entities[75],
        ["Spaarker"]=entities[76],
        ["Synthetic Horf"]=entities[77],
        ["Pallun"]=entities[78],
        ["Ulig"]=entities[79],
        ["Sixhead Top"]=entities[80],
        ["Sixhead Bottom"]=entities[81],
        ["Mush Loom"]=entities[82],
        ["Harmoor"]=entities[83],
        ["Pit Pat Spawner"]=entities[84],
        ["Pit Pat"]=entities[85],
        ["Babble"]=entities[86],
        ["Erythorcyte"]=entities[87],
        ["Erythorcytebaby"]=entities[88],
        ["Stone Johnny"]=entities[89],
        ["Wost"]=entities[90],
        ["Souwa"]=entities[91],
        ["Rain Monger"]=entities[92],
        ["Zapper Teller"]=entities[93],
        ["Pinprick"]=entities[94],
        ["Wisp Wosp"]=entities[95],
        ["Drosslet"]=entities[96],
        ["Gassed Fly"]=entities[97],
        ["Stuckpoot"]=entities[98],
        ["Jim"]=entities[99],
        ["Tech Grudge"]=entities[100],
        ["Fear Flower"]=entities[101],
        ["Clatter Teller"]=entities[102],
        ["Dekatessera"]=entities[103],
        ["Fivedead"]=entities[104],
        ["Onedead"]=entities[105],
        ["Tainted Silly"]=entities[106],
        ["Tainted String"]=entities[107],
        ["&"]=entities[108],
        ["Tainted Web Mother"]=entities[109],
        ["Tainted Yoyader"]=entities[110],
        ["Narcissism"]=entities[111],
        ["Chomb"]=entities[112],
        ["Narcissism Reflections"]=entities[113],
        ["Narcissism Mirror"]=entities[114],
        ["Chomblet"]=entities[115],
        ["Sam"]=entities[116],
        ["Sam Bear Spawn"]=entities[117],
        ["Hop"]=entities[118],
        ["Skip"]=entities[119],
        ["Jump"]=entities[120],
        ["Chris"]=entities[121],
        ["A gaper w/ three legs, why did we do this"]=entities[122],
        ["Willowalker"]=entities[123],
        ["Bowl of Sauerkraut"]=entities[124],
        ["Letter To Myself"]=entities[125],
        ["Birthday Slice"]=entities[126],
        ["Snark (Half Life)"]=entities[128],
        ["Marketable Plushie Familiar"]=entities[129],
        ["Lil' Ana"]=entities[130],
        ["Breakable Pot"]=entities[131],
        ["Blank NPC"]=entities[132],
        ["Error Room Editor"]=entities[133],
        ["Blank Effect"]=entities[134],
        ["Zapper Teller Lightning"]=entities[135],
        ["BlackOverlayBox"]=entities[136],
        ["Text Box"]=entities[137],
        ["Clatter Teller Target"]=entities[138],
        ["Fear Flower Fear"]=entities[139],
        ["Dekatessera Effect"]=entities[140],
        ["Rain Grid Effect"]=entities[141],
        ["Large Spiderweb"]=entities[142],
        ["Fire Projectile"]=entities[143],
        ["OGWilloWalker Box"]=entities[144],
        ["OGWilloWalker Font"]=entities[145],
        ["Ruin NPC"]=entities[146],
        ["OGWilloWalker"]=entities[147],
        ["Ember Projectile"]=entities[148],
        ["HOPE Grid Spawner"]=entities[149],
        ["Light Pressure Plate Null Entity"]=entities[150],
        ["Quiz Question Placement"]=entities[151],
        ["IsMoQu Custom Grid Spawn"]=entities[152],}
    elseif mode == 3 then
        return {[161]={[0]={[0]=entities[1],},[1]={[0]=entities[2],},[2]={[0]=entities[3],},[4]={[0]=entities[4],
        [1]=entities[5],
        [2]=entities[6],
        [3]=entities[7],
        [4]=entities[8],
        [5]=entities[9],
        [6]=entities[10],
        [7]=entities[11],
        [8]=entities[12],},[5]={[0]=entities[13],},[6]={[0]=entities[14],},[7]={[0]=entities[15],},[9]={[0]=entities[16],},[11]={[0]=entities[17],},[12]={[0]=entities[104],},[13]={[1]=entities[105],},[16]={[0]=entities[20],},[21]={[0]=entities[21],},[26]={[0]=entities[22],},[27]={[0]=entities[23],},[30]={[0]=entities[24],},[35]={[0]=entities[25],},[36]={[0]=entities[26],},[37]={[0]=entities[27],},[38]={[0]=entities[28],},[44]={[0]=entities[29],},[40]={[0]=entities[30],},[43]={[0]=entities[31],},[46]={[0]=entities[32],},[50]={[0]=entities[33],
        [1]=entities[34],
        [2]=entities[35],
        [3]=entities[36],},[41]={[0]=entities[37],
        [1]=entities[38],
        [2]=entities[39],
        [3]=entities[40],
        [4]=entities[41],
        [5]=entities[42],
        [6]=entities[43],},[51]={[0]=entities[44],
        [1]=entities[45],
        [2]=entities[46],
        [3]=entities[47],
        [4]=entities[48],
        [5]=entities[49],
        [6]=entities[50],},[53]={[0]=entities[51],},[42]={[0]=entities[52],},[45]={[0]=entities[54],},[47]={[0]=entities[55],},[48]={[0]=entities[56],},[49]={[0]=entities[57],},[52]={[0]=entities[58],},[59]={[0]=entities[59],},[65]={[0]=entities[60],},[71]={[0]=entities[63],},[72]={[0]=entities[64],},[73]={[0]=entities[65],},[75]={[0]=entities[66],},[79]={[0]=entities[67],},[81]={[0]=entities[68],},[80]={[0]=entities[69],},[84]={[0]=entities[70],},[91]={[0]=entities[71],},[97]={[0]=entities[72],},[100]={[0]=entities[73],},[101]={[0]=entities[74],},[105]={[0]=entities[75],},[108]={[0]=entities[76],},[189]={[0]=entities[77],},[202]={[0]=entities[78],},[203]={[0]=entities[79],},[210]={[0]=entities[80],},[211]={[0]=entities[81],},[224]={[0]=entities[82],},[273]={[0]=entities[83],},[278]={[1]=entities[84],
        [0]=entities[85],},[420]={[0]=entities[86],},[400]={[0]=entities[87],
        [1]=entities[88],},[109]={[0]=entities[89],},[119]={[0]=entities[90],},[121]={[0]=entities[91],},[124]={[0]=entities[92],},[133]={[0]=entities[93],},[145]={[0]=entities[94],},[144]={[0]=entities[95],},[169]={[0]=entities[96],},[177]={[0]=entities[97],},[167]={[0]=entities[98],},[311]={[0]=entities[100],},[532]={[0]=entities[101],},[535]={[0]=entities[102],},[537]={[0]=entities[103],},[4095]={[0]=entities[132],},[4089]={[0]=entities[150],},},[37]={[3]={[0]=entities[53],},[100]={[0]=entities[99],},[4]={[0]=entities[113],},[2]={[0]=entities[114],},[5]={[0]=entities[115],},[6]={[0]=entities[117],},},[240]={[359]={[0]=entities[61],},[368]={[0]=entities[62],},},[426]={[0]={[0]=entities[106],},[1]={[0]=entities[107],},[2]={[0]=entities[108],},[3]={[0]=entities[109],},[4]={[0]=entities[110],},},[95]={[0]={[0]=entities[111],},[1]={[0]=entities[112],},[2]={[0]=entities[116],},},[136]={[0]={[0]=entities[118],},[1]={[0]=entities[119],},[2]={[0]=entities[120],},[3]={[0]=entities[121],},},[10]={[5938]={[0]=entities[122],},},[137]={[3939]={[0]=entities[123],},},[5]={[721]={[0]=entities[124],},[722]={[0]=entities[125],},[300]={[451]=entities[126],
        [452]=entities[127],},},[3]={[4502]={[0]=entities[128],},[4503]={[0]=entities[129],},[4504]={[0]=entities[130],},},[753]={[950]={[0]=entities[131],},},[998]={[418]={[0]=entities[133],},},[1000]={[419]={[0]=entities[134],},[420]={[0]=entities[135],},[421]={[0]=entities[136],},[424]={[0]=entities[137],},[425]={[0]=entities[138],},[426]={[0]=entities[139],},[427]={[0]=entities[140],},[432]={[0]=entities[141],},[428]={[0]=entities[142],},[431]={[0]=entities[143],},[429]={[0]=entities[144],},[430]={[0]=entities[145],},},[163]={[0]={[0]=entities[146],},[2]={[0]=entities[147],},},[9]={[0]={[0]=entities[148],},},[162]={[0]={[0]=entities[149],},},[982]={[419]={[0]=entities[151],},},[634]={[0]={[0]=entities[152],},},}
    end    
end

