function FHAC:LoadScripts(includestart, t)
    for k, v in ipairs(t) do
        if includestart then v= includestart.."." .. v end
        include(v)
    end
end

local presumedentitires = {
"Box",
"Plooper",
"Peacter",
"Log",
"Sucka",
"Mismatch",
"Grabby",
"Neutral Fly",
"Thread",
"Puzzle Piece",
"Wee Stee",
"Pit Monster",
"Gobbo",
"Sho",
"Mr Belly",
"Belly Guts",
"Stoner",
"Cronic Laser",
"Poo Nibbler",
"Silk",
"Treacherous Floater",
"Christy Longhedge",
"Silly",
"Missy",
"The Hanged",
"Hangeslip",
"Scraping",
"Dried",
"Plier",
"Cube Baby",
"Scaredy Creep",
"Nib",
"Plasticized",
"String",
"Pit Bee",
"Mouster",
"Awachnid",
"Rocky Tocky",
"Scooterbrained",
"Growm",
"Banoonoo",
"Log a Nog",
"Uncharged",
"Outlet",
"Bot Dud",
"Coin Spooder",
"Plank Boi",
"Moost",
"Tagger",
"Scarly",
"Iced Liver",
"Filler Up",
"Etirte",
"Droppling",
"Prezzie",
"Sack",
"Floor Creep",
"Spilt",
"Scorched Sooter",
"Flame Sufferer",
"Facebalm",
"Flickerwisp",
"Sunfer",
"Lil’ Flash",
"Crackling Host",
"Scorched Peat",
"Woosp",
"Flaming Polti",
"Smokey - Roakey",
"Scorchful Worm",
"Trilo",
"Bloop",
"Smoked Spooter",
"Bonefire",
"Crisp Cube Baby",
"Charred Stoned",
"Inflamed Dip",
"Schmoot",
"Fire in the Wall",
"Derping",
"Wagma",
"Wrath’s Baby",
"Spursmoke",
"Fronk",
"Solpo",
"Sulferer",
"Scutch",
"Lame Claim n’ Blame Flame Flower",
"Hotbrain",
"Overburnt",
"Taki",
"Embolzon",
"Sojourner",
"Flame - Negative",
"Sparker",
"Stone Johnny",
"Gobwet",
"Spluttering",
"Interminator",
"Wet Fly",
"Upsie Pooter",
"Pipe",
"Smol Icy",
"Lil’ Morbo",
"Lime Morbo",
"Wost",
"Wolter",
"Souwa",
"Bezzie",
"I - Slob",
"Rain Monger",
"Eddie",
"Sploota",
"Lvl 2.5 Spider",
"Wolloder",
"Lil’ Bulb",
"Big Bulb",
"Waiting Post",
"Dishock",
"Zapper - Teller",
"Wawachnid",
"‘Brellaneer",
"Downpour Grimace",
"Ethereal Pest",
"Wet Spider",
"Mr. Stoot",
"Ethereal Spurter",
"Ethereal Idiot",
"Stoot Head",
"Stormcaller",
"Wisp Wosp",
"Pinprick",
"Ethereal Nest",
"Hostmettle",
"Gulfulous Dangler",
"Turdlings",
"Mud Cake",
"Shit Fly",
"Wiss Piss",
"Shit Boi",
"Stone Pisser",
"Floating Shit",
"Cornpall",
"Toilet Seat",
"Turdwee",
"Sumph and Dump",
"Doggy Bag",
"Side Pour",
"Bumfold",
"Grumbold",
"Toilet Paper",
"Sewer Rat",
"Mareeyo",
"Stuckpoot",
"Foomper",
"Drosslet - Aeroace",
"Thickun",
"Anal Stone",
"Poopter",
"Gloost",
"Trail",
"Gloo",
"Patty Hands",
"Gassed Fly",
"Pit - Pat",
"Dump’d",
"Gutter",
"Full Cup",
"Plantain",
"Shit Fingers",
"LvL 2 Cyclops",
"Gobsob",
"Infested 2",
"Cave Fly",
"Cave Spider",
"LvL 2 Floater",
"Synthetic Horf",
"Custom",
"Bollyier",
"Test Subject",
"Glugging",
"Boll Charger",
"Rumboo",
"Diplo Pooter",
"LvL 2 Angry Spider",
"Bonerm",
"Pissed Stoner",
"Blushing Tot",
"Pallun",
"Hive Boy",
"Wall &%$#",
"Kermee",
"Wall Pest",
"Enchantelret",
"LvL 3 Fly",
"Dead Crackle",
"Bottom",
"Estrooged",
"Sixhead",
"Capped",
"LvL 2 Grimace",
"Tentickle",
"Cave Skull",
"Run n’ Gun",
"Bat Fly",
"Roundy",
"Cursed Topiary",
"Stone Golem",
"Funguy",
"Wee Floes",
"Mush Loom",
"Voodon’t",
"Soddon Painting",
"Ms Belly",
"Weightloft",
"Whistle",
"Book Lurk",
"Cybabe",
"Limberwolf",
"Hobby Horse Skull",
"Gravedigger",
"Deadbeat",
"LvL 2 Rocker",
"Pan Flute",
"Ploat Boat",
"Snicklard",
"Webbed Stoned",
"Cart Dealer",
"Costumed Floater",
"Snake",
"Hide n’ Seek",
"Knight Hart",
"Brimney Stupe Hand",
"Scarred Skull",
"Willo Wisp",
"Folio Foilage",
"Cobbed Peactner",
"Tightneck",
"Grover",
"FockRoach",
"SquoBlow",
"Lovocado",
"Befouled Folio",
"Colfel Server",
"Bean Grinder",
"Navalrot",
"Stuffed Boom Fly",
"Spear of Destiny",
"Soup Bowl",
"Ambrage",
"Statue",
"Zombie",
"Zombie Head",
"Zombie Body",
"Brainlets",
"Paper Horf",
"Grasslet",
"Monk",
"Lil’ Minnow",
"Harmoor - ",
"Jellyinn",
"Soaker",
"Orb",
"Waterpall",
"PitPat",
"Soaked Worm",
"Slimy Charger",
"Overcast",
"Neutral Spider",
"Pickleport",
"Glurgle",
"Lurken",
"Undercast",
"Tide Sprinter",
"Wet Skull",
"Creep Girl",
"Plop",
"Slop",
"Cock and Toad",
"Infloasted 2",
"Trio (All 3 Subtypes)",
"Kukioro",
"Burst Blower",
"Soakin’ Floater",
"Hallucitin’",
"Skipper",
"Ploptin",
"Ola",
"Reed",
"Bloated",
"Splooper",
"Peerc Gloo",
"Sloaden",
"Fullun’",
"GobDronk",
"Miner",
"BuckTag",
"Tech Grudge",
"Lava Spurter",
"Eyebord",
"Angry Miner",
"Rock Fly",
"Gas Imp",
"Air Minor",
"Lantern",
"Ston - Ston",
"Mines Grimace",
"Rock Collector",
"Mausoleum Sludge",
"Dragon Bat",
"Rock Stock",
"Tool",
"Task Fool",
"Haunted Cart",
"Drill Minor",
"Meat Sweep",
"Conjoined Meat",
"Megdroll",
"Fairy Bright",
"Spider Buster",
"Teartaster",
"Wall Crawl",
"Flinch",
"Tooth",
"Grilled Conjoined Meat",
"Tofu Boy",
"Engineer",
"Tech Stony",
"Bodyless",
"Meat Clover",
"Floating Fat",
"Lavalet",
"Infired Egg",
"Hottentot",
"Rocky Dip",
"Buried Grudge",
"Tract-Tract",
"Flesh Worm",
"Dust Bunny",
"Rollercoastarian",
"Crushin’",
"Leper",
"Lost Bones",
"Dust Tornado",
"Dust Spider",
"Mattoer",
"Flesh Worm",
"Sopping Meat",
"Dust Clencher",
"Toppli",
"Psych Fly",
"Ghost Sucka",
"Rag Boi",
"Flesh Floater",
"Sack Spider",
"Meatsaac",
"Floor Crepe",
"Bungee",
"Balls Rider",
"Stony Corpse",
"Coal Fly",
"Rock Brain",
"Ground Grimace",
"Toasted",
"Lase Rider",
"Duston",
"Grilled Meatsaac",
"Flesh Fly",
"Pallun Worm",
"Dundust",
"1.5 Fountain",
"Bimbo",
"Bled Head",
"Dark Beetle",
"Trip",
"Flesh",
"Stone",
"Insecure",
"Mr Float",
"Level 1.9 Fly",
"Gruggy",
"Vister",
"Level 1.9 Spider",
"Stone Faced Creep",
"Metal Head",
"Neb",
"Level 3 Stoner",
"St Larothy",
"The Mutant",
"Ishmael",
"Level 3 Spooder",
"Assassin Fly",
"Mass",
"Visataly",
"Husklie",
"Magnot",
"Undeath",
"Lympho",
"Trumal",
"Stub",
"Monistro",
"Chompa",
"Brain Worm",
"Splithead",
"Shortstace",
"Death Peactner",
"Sunni Fly",
"Gooey Knight",
"Globful",
"Dapbe",
"Pincuwa",
"Bubbling",
"Oily Blob",
"Sliol Charger",
"Dank Stony",
"Ronky",
"Soft Shit",
"Shit Piece",
"Dank Sulker",
"Dank Brown",
"Poplap",
"Soaking Tumor",
"Slimy Stoner",
"Troager",
"Floating Slob",
"Swinger",
"Dystopia",
"Brunger",
"Bat-loon",
"Pit Parasite",
"Mite Spite",
"Cuplet",
"Ass Class",
"Quarterback",
"Splacter",
"Globset",
"Maybe",
"Infoosted",
"C. Abuss",
"Flagholder",
"Low Strung",
"Soldier",
"Wall Boner",
"Bonehead",
"Rottie",
"Wall Watch",
"Manifesta",
"Beno",
"Poster",
"Boned",
"Dudock",
"Ma",
"Possessment",
"Ribbder",
"Undead Patient",
"Burlap",
"Malted",
"Skeledar",
"Galah",
"Conga",
"Mr. Lament",
"Coaster",
"Pain Golem",
"Coal Shoulder",
"Psychosweep",
"Bouncer",
"A! Edith",
"Heads of Apostasy",
"Visonaire",
"Psycho Floater",
"No-Mouth",
"Maintenance Manager",
"Psychults Holder",
"Overseer’s Assistant",
"Tracker",
"Wall Stalker",
"Candler",
"Doric Zealot",
"Skull Loom",
"Archer",
"Howler",
"Psychic Fivehead",
"Gaper (Purgatory)",
"Hooker",
"Flagger",
"Tarot Cot",
"Loomer",
"Purgatory Heart",
"Teepee",
"Nightmare Catcher",
"Cyclops (Purgatory)",
"Bell Clanger",
"Collapser",
"Parer",
"Guided",
"Ghositter",
"Ghosheart",
"Headless Horf",
"Sharpener",
"Lurquen",
"Mimimace",
"Gampie",
"Zipper",
"Gamy",
"Thwammy Jr",
"Solagratia",
"Swooper",
"Summoning Circle",
"Hanging Mines",
"Agons",
"Gloomies",
"Chapell",
"Victim’s Ring",
"Lil’ Rider",
}

if StageAPI and StageAPI.Loaded then
StageAPI.UnregisterCallbacks("FHAC")
FHAC:LoadScripts("scripts", {
	"savedata",
	"constants",
	"library",
	"iam.main",
	"callbacks",
	"iam.misc.resources.fortunes",
	"items",
	"entities2",
	"compatability.fiend folio.modcompact",
	"otherapi.fiend folio.api.fortunehandling",
	"otherapi.fiend folio.api.apioverride",
	"otherapi.proapi.proapi",
	"deathtransform",
})
--iam stuff
FHAC:LoadScripts("scripts.iam.monsters", {
	"fivehead",
	"floater",
	"neutralfly",
	"patient",
	"dried",
	"erythorcyte",
	"wost",
	"schmoot",
	"snidge",
	"drosslet",
	"pitpat",
	"mushloom",
	"pinprick",
	"synthetichorf",
	"gassedfly",
	"fly_ve-bomber", --HAHAHAH FUCK YOU EUAN TOO
	"pallun",
	"sillystring",
	"stickyfly",
	"wispwosp",
	"stuckpoot",
	"rainmonger",
	"zapperteller",
	"techgrudge",
	"log",
	"stoner",
	"lightpressureplatenullent",
	"larrykingjr",
	"bottom",
	"sixhead",
	"babble"
})

FHAC:LoadScripts("scripts.iam.monsters", presumedentitires)

FHAC:LoadScripts("scripts.iam", {
	"cvsunlocks",
	"levelreplaceshit",
	"customgrids"
})

FHAC:LoadScripts("scripts.iam.effects", {
	"zapperteller_lightning",
	"blackboxoverlay"
})

FHAC:LoadScripts("scripts.iam.familiars", {
	"snark",
})

FHAC:LoadScripts("scripts.iam.items.actives", {
	"joke book",
	"straw doll"
})

FHAC:LoadScripts("scripts.iam.items.passives", {
	"stinky mushroom",
	"anal fissure",
	"big ol' bowl of sauerkraut"
})

FHAC:LoadScripts("scripts.iam.jokes", {
	"gaprrr",
})

if not FHAC.hasloadedDSS then
	FHAC:LoadScripts("scripts.iam.deadseascrolls", {
		"dssmain",
	})
	FHAC.hasloadedDSS = true
end

FHAC:LoadScripts("scripts.iam.characters", {
	"johannes",
	"johannesb",
	"pongon"
})

FHAC:LoadScripts("scripts.iam.challenges", {
	"therealbestiary",
})
else
	include("scripts.iam.misc.warning")
end
